// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package workflowtype

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkflowIn struct {
	Data                 *string  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowIn) Reset()         { *m = WorkflowIn{} }
func (m *WorkflowIn) String() string { return proto.CompactTextString(m) }
func (*WorkflowIn) ProtoMessage()    {}
func (*WorkflowIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *WorkflowIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowIn.Unmarshal(m, b)
}
func (m *WorkflowIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowIn.Marshal(b, m, deterministic)
}
func (m *WorkflowIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowIn.Merge(m, src)
}
func (m *WorkflowIn) XXX_Size() int {
	return xxx_messageInfo_WorkflowIn.Size(m)
}
func (m *WorkflowIn) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowIn.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowIn proto.InternalMessageInfo

func (m *WorkflowIn) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type WorkflowBasicOut struct {
	DBOut                *DBOut   `protobuf:"bytes,1,req,name=DBOut" json:"DBOut,omitempty"`
	GitOut               *GitOut  `protobuf:"bytes,2,req,name=GitOut" json:"GitOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowBasicOut) Reset()         { *m = WorkflowBasicOut{} }
func (m *WorkflowBasicOut) String() string { return proto.CompactTextString(m) }
func (*WorkflowBasicOut) ProtoMessage()    {}
func (*WorkflowBasicOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *WorkflowBasicOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowBasicOut.Unmarshal(m, b)
}
func (m *WorkflowBasicOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowBasicOut.Marshal(b, m, deterministic)
}
func (m *WorkflowBasicOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowBasicOut.Merge(m, src)
}
func (m *WorkflowBasicOut) XXX_Size() int {
	return xxx_messageInfo_WorkflowBasicOut.Size(m)
}
func (m *WorkflowBasicOut) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowBasicOut.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowBasicOut proto.InternalMessageInfo

func (m *WorkflowBasicOut) GetDBOut() *DBOut {
	if m != nil {
		return m.DBOut
	}
	return nil
}

func (m *WorkflowBasicOut) GetGitOut() *GitOut {
	if m != nil {
		return m.GitOut
	}
	return nil
}

type WorkflowAsyncV1Out struct {
	DBOut                *DBOut   `protobuf:"bytes,1,req,name=DBOut" json:"DBOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowAsyncV1Out) Reset()         { *m = WorkflowAsyncV1Out{} }
func (m *WorkflowAsyncV1Out) String() string { return proto.CompactTextString(m) }
func (*WorkflowAsyncV1Out) ProtoMessage()    {}
func (*WorkflowAsyncV1Out) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *WorkflowAsyncV1Out) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowAsyncV1Out.Unmarshal(m, b)
}
func (m *WorkflowAsyncV1Out) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowAsyncV1Out.Marshal(b, m, deterministic)
}
func (m *WorkflowAsyncV1Out) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowAsyncV1Out.Merge(m, src)
}
func (m *WorkflowAsyncV1Out) XXX_Size() int {
	return xxx_messageInfo_WorkflowAsyncV1Out.Size(m)
}
func (m *WorkflowAsyncV1Out) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowAsyncV1Out.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowAsyncV1Out proto.InternalMessageInfo

func (m *WorkflowAsyncV1Out) GetDBOut() *DBOut {
	if m != nil {
		return m.DBOut
	}
	return nil
}

type WorkflowAsyncV2Out struct {
	DBOut                *DBOut   `protobuf:"bytes,1,req,name=DBOut" json:"DBOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowAsyncV2Out) Reset()         { *m = WorkflowAsyncV2Out{} }
func (m *WorkflowAsyncV2Out) String() string { return proto.CompactTextString(m) }
func (*WorkflowAsyncV2Out) ProtoMessage()    {}
func (*WorkflowAsyncV2Out) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *WorkflowAsyncV2Out) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowAsyncV2Out.Unmarshal(m, b)
}
func (m *WorkflowAsyncV2Out) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowAsyncV2Out.Marshal(b, m, deterministic)
}
func (m *WorkflowAsyncV2Out) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowAsyncV2Out.Merge(m, src)
}
func (m *WorkflowAsyncV2Out) XXX_Size() int {
	return xxx_messageInfo_WorkflowAsyncV2Out.Size(m)
}
func (m *WorkflowAsyncV2Out) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowAsyncV2Out.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowAsyncV2Out proto.InternalMessageInfo

func (m *WorkflowAsyncV2Out) GetDBOut() *DBOut {
	if m != nil {
		return m.DBOut
	}
	return nil
}

type WorkflowAsyncV2Status struct {
	Status               *string             `protobuf:"bytes,1,req,name=Status" json:"Status,omitempty"`
	Completed            *bool               `protobuf:"varint,2,req,name=Completed" json:"Completed,omitempty"`
	Result               *WorkflowAsyncV2Out `protobuf:"bytes,3,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WorkflowAsyncV2Status) Reset()         { *m = WorkflowAsyncV2Status{} }
func (m *WorkflowAsyncV2Status) String() string { return proto.CompactTextString(m) }
func (*WorkflowAsyncV2Status) ProtoMessage()    {}
func (*WorkflowAsyncV2Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *WorkflowAsyncV2Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowAsyncV2Status.Unmarshal(m, b)
}
func (m *WorkflowAsyncV2Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowAsyncV2Status.Marshal(b, m, deterministic)
}
func (m *WorkflowAsyncV2Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowAsyncV2Status.Merge(m, src)
}
func (m *WorkflowAsyncV2Status) XXX_Size() int {
	return xxx_messageInfo_WorkflowAsyncV2Status.Size(m)
}
func (m *WorkflowAsyncV2Status) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowAsyncV2Status.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowAsyncV2Status proto.InternalMessageInfo

func (m *WorkflowAsyncV2Status) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *WorkflowAsyncV2Status) GetCompleted() bool {
	if m != nil && m.Completed != nil {
		return *m.Completed
	}
	return false
}

func (m *WorkflowAsyncV2Status) GetResult() *WorkflowAsyncV2Out {
	if m != nil {
		return m.Result
	}
	return nil
}

type WorkflowSideEffectOut struct {
	DBOut                *DBOut         `protobuf:"bytes,1,req,name=DBOut" json:"DBOut,omitempty"`
	GitOut               *GitOut        `protobuf:"bytes,2,req,name=GitOut" json:"GitOut,omitempty"`
	SideEffectOut        *SideEffectOut `protobuf:"bytes,3,req,name=SideEffectOut" json:"SideEffectOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WorkflowSideEffectOut) Reset()         { *m = WorkflowSideEffectOut{} }
func (m *WorkflowSideEffectOut) String() string { return proto.CompactTextString(m) }
func (*WorkflowSideEffectOut) ProtoMessage()    {}
func (*WorkflowSideEffectOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *WorkflowSideEffectOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowSideEffectOut.Unmarshal(m, b)
}
func (m *WorkflowSideEffectOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowSideEffectOut.Marshal(b, m, deterministic)
}
func (m *WorkflowSideEffectOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowSideEffectOut.Merge(m, src)
}
func (m *WorkflowSideEffectOut) XXX_Size() int {
	return xxx_messageInfo_WorkflowSideEffectOut.Size(m)
}
func (m *WorkflowSideEffectOut) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowSideEffectOut.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowSideEffectOut proto.InternalMessageInfo

func (m *WorkflowSideEffectOut) GetDBOut() *DBOut {
	if m != nil {
		return m.DBOut
	}
	return nil
}

func (m *WorkflowSideEffectOut) GetGitOut() *GitOut {
	if m != nil {
		return m.GitOut
	}
	return nil
}

func (m *WorkflowSideEffectOut) GetSideEffectOut() *SideEffectOut {
	if m != nil {
		return m.SideEffectOut
	}
	return nil
}

type DBOut struct {
	ID                   *string  `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBOut) Reset()         { *m = DBOut{} }
func (m *DBOut) String() string { return proto.CompactTextString(m) }
func (*DBOut) ProtoMessage()    {}
func (*DBOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *DBOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBOut.Unmarshal(m, b)
}
func (m *DBOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBOut.Marshal(b, m, deterministic)
}
func (m *DBOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBOut.Merge(m, src)
}
func (m *DBOut) XXX_Size() int {
	return xxx_messageInfo_DBOut.Size(m)
}
func (m *DBOut) XXX_DiscardUnknown() {
	xxx_messageInfo_DBOut.DiscardUnknown(m)
}

var xxx_messageInfo_DBOut proto.InternalMessageInfo

func (m *DBOut) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

type DBOutWithSideEffect struct {
	DBOut                *DBOut         `protobuf:"bytes,1,req,name=DBOut" json:"DBOut,omitempty"`
	SideEffectOut        *SideEffectOut `protobuf:"bytes,2,req,name=SideEffectOut" json:"SideEffectOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DBOutWithSideEffect) Reset()         { *m = DBOutWithSideEffect{} }
func (m *DBOutWithSideEffect) String() string { return proto.CompactTextString(m) }
func (*DBOutWithSideEffect) ProtoMessage()    {}
func (*DBOutWithSideEffect) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *DBOutWithSideEffect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBOutWithSideEffect.Unmarshal(m, b)
}
func (m *DBOutWithSideEffect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBOutWithSideEffect.Marshal(b, m, deterministic)
}
func (m *DBOutWithSideEffect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBOutWithSideEffect.Merge(m, src)
}
func (m *DBOutWithSideEffect) XXX_Size() int {
	return xxx_messageInfo_DBOutWithSideEffect.Size(m)
}
func (m *DBOutWithSideEffect) XXX_DiscardUnknown() {
	xxx_messageInfo_DBOutWithSideEffect.DiscardUnknown(m)
}

var xxx_messageInfo_DBOutWithSideEffect proto.InternalMessageInfo

func (m *DBOutWithSideEffect) GetDBOut() *DBOut {
	if m != nil {
		return m.DBOut
	}
	return nil
}

func (m *DBOutWithSideEffect) GetSideEffectOut() *SideEffectOut {
	if m != nil {
		return m.SideEffectOut
	}
	return nil
}

type GitOut struct {
	ID                   *string  `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitOut) Reset()         { *m = GitOut{} }
func (m *GitOut) String() string { return proto.CompactTextString(m) }
func (*GitOut) ProtoMessage()    {}
func (*GitOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *GitOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitOut.Unmarshal(m, b)
}
func (m *GitOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitOut.Marshal(b, m, deterministic)
}
func (m *GitOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitOut.Merge(m, src)
}
func (m *GitOut) XXX_Size() int {
	return xxx_messageInfo_GitOut.Size(m)
}
func (m *GitOut) XXX_DiscardUnknown() {
	xxx_messageInfo_GitOut.DiscardUnknown(m)
}

var xxx_messageInfo_GitOut proto.InternalMessageInfo

func (m *GitOut) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

type SideEffectOut struct {
	Message              *string  `protobuf:"bytes,1,req,name=Message" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SideEffectOut) Reset()         { *m = SideEffectOut{} }
func (m *SideEffectOut) String() string { return proto.CompactTextString(m) }
func (*SideEffectOut) ProtoMessage()    {}
func (*SideEffectOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *SideEffectOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SideEffectOut.Unmarshal(m, b)
}
func (m *SideEffectOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SideEffectOut.Marshal(b, m, deterministic)
}
func (m *SideEffectOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SideEffectOut.Merge(m, src)
}
func (m *SideEffectOut) XXX_Size() int {
	return xxx_messageInfo_SideEffectOut.Size(m)
}
func (m *SideEffectOut) XXX_DiscardUnknown() {
	xxx_messageInfo_SideEffectOut.DiscardUnknown(m)
}

var xxx_messageInfo_SideEffectOut proto.InternalMessageInfo

func (m *SideEffectOut) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkflowIn)(nil), "workflowtype.WorkflowIn")
	proto.RegisterType((*WorkflowBasicOut)(nil), "workflowtype.WorkflowBasicOut")
	proto.RegisterType((*WorkflowAsyncV1Out)(nil), "workflowtype.WorkflowAsyncV1Out")
	proto.RegisterType((*WorkflowAsyncV2Out)(nil), "workflowtype.WorkflowAsyncV2Out")
	proto.RegisterType((*WorkflowAsyncV2Status)(nil), "workflowtype.WorkflowAsyncV2Status")
	proto.RegisterType((*WorkflowSideEffectOut)(nil), "workflowtype.WorkflowSideEffectOut")
	proto.RegisterType((*DBOut)(nil), "workflowtype.DBOut")
	proto.RegisterType((*DBOutWithSideEffect)(nil), "workflowtype.DBOutWithSideEffect")
	proto.RegisterType((*GitOut)(nil), "workflowtype.GitOut")
	proto.RegisterType((*SideEffectOut)(nil), "workflowtype.SideEffectOut")
}

func init() {
	proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355)
}

var fileDescriptor_d938547f84707355 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xde, 0xd7, 0x68, 0xa7, 0x2a, 0x32, 0xf5, 0x4f, 0x40, 0x0f, 0x61, 0x4f, 0x16,
	0x24, 0x60, 0x4f, 0xde, 0xa4, 0x35, 0x22, 0x39, 0x48, 0x61, 0x0b, 0xf6, 0x1c, 0xd2, 0x8d, 0x86,
	0xc6, 0x26, 0x74, 0x27, 0x94, 0x9e, 0x3d, 0xf8, 0x81, 0xfc, 0x82, 0xd2, 0xcd, 0x86, 0x76, 0x9b,
	0x53, 0x0e, 0xde, 0x76, 0x76, 0x7e, 0xf3, 0x3c, 0xcf, 0x0c, 0x74, 0x69, 0x5d, 0x08, 0xe9, 0x17,
	0xcb, 0x9c, 0x72, 0x3c, 0x5e, 0xe5, 0xcb, 0x79, 0x92, 0xe5, 0xab, 0xcd, 0x27, 0xf3, 0x00, 0xa6,
	0xba, 0x0e, 0x17, 0x88, 0xf0, 0x3f, 0x88, 0x28, 0x72, 0x2d, 0xcf, 0xbe, 0xed, 0x70, 0xf5, 0x66,
	0x73, 0x38, 0xab, 0x89, 0x51, 0x24, 0xd3, 0x78, 0x5c, 0x12, 0xf6, 0xe1, 0x20, 0x18, 0x8d, 0x4b,
	0x52, 0x60, 0x77, 0xd0, 0xf3, 0x77, 0x35, 0x7d, 0xd5, 0xe2, 0x15, 0x81, 0x77, 0xe0, 0xbc, 0xa4,
	0xb4, 0x61, 0x6d, 0xc5, 0x9e, 0x9b, 0x6c, 0xd5, 0xe3, 0x9a, 0x61, 0x8f, 0x80, 0xb5, 0xd9, 0x50,
	0xae, 0x17, 0xf1, 0xdb, 0x7d, 0x3b, 0xbb, 0xa6, 0xc0, 0xa0, 0xa5, 0xc0, 0xb7, 0x05, 0x17, 0x7b,
	0x0a, 0x13, 0x8a, 0xa8, 0x94, 0x78, 0x09, 0x4e, 0xf5, 0xd2, 0xe7, 0xd1, 0x15, 0xde, 0x40, 0xe7,
	0x29, 0xff, 0x2c, 0x32, 0x41, 0x62, 0xa6, 0x96, 0x3c, 0xe2, 0xdb, 0x0f, 0x7c, 0x00, 0x87, 0x0b,
	0x59, 0x66, 0xe4, 0xfe, 0x53, 0xde, 0x9e, 0xe9, 0xdd, 0x0c, 0xcb, 0x35, 0xcf, 0x7e, 0x76, 0x92,
	0x4c, 0xd2, 0x99, 0x78, 0x4e, 0x12, 0x11, 0xd3, 0x5f, 0x9e, 0x1f, 0x87, 0x70, 0x62, 0x38, 0xe9,
	0xcc, 0xd7, 0xe6, 0x90, 0x81, 0x70, 0x73, 0x82, 0x5d, 0xe9, 0x6c, 0x78, 0x0a, 0x76, 0x18, 0xe8,
	0x53, 0xd9, 0x61, 0xc0, 0xbe, 0x2c, 0xe8, 0xa9, 0xce, 0x34, 0xa5, 0x8f, 0xed, 0x4c, 0x9b, 0x65,
	0x1a, 0xf1, 0xec, 0xd6, 0xf1, 0xdc, 0xfa, 0x1e, 0x8d, 0x7c, 0xfd, 0x3d, 0x71, 0x74, 0xe1, 0xf0,
	0x55, 0x48, 0x19, 0xbd, 0x0b, 0x4d, 0xd5, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0xc3,
	0xc4, 0x4b, 0x50, 0x03, 0x00, 0x00,
}
